language: node_js
cache:
  directories:
  - node_modules
install:
  - yarn install
script:
  - export PUBLIC_URL=https://cs498-cloud-group1.github.io/MapReduceUI/
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the travis settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
